import type { Company } from "../types/company-types";

export const INITIAL_COMPANIES: Company[] = [
  {
    id: "bu-101",
    name: "Northwind Retail Inc",
    key: "northwind-retail",
    status: "Active",
    unitType: "Company",
    storeKey: "us-flagship-store",
    createdAt: "2026-01-15T09:30:00Z",
    lastModifiedAt: "2026-08-01T14:20:00Z",
    creditLimit: 50000,
    creditUsed: 12450,
    addresses: [
      {
        id: "addr-101",
        companyName: "Northwind HQ",
        streetName: "Fifth Avenue",
        streetNumber: "742",
        building: "Suite 500",
        city: "New York",
        postalCode: "10001",
        state: "NY",
        country: "US",
        isDefaultShipping: true,
        isDefaultBilling: true,
      },
      {
        id: "addr-102",
        companyName: "Northwind West Warehouse",
        streetName: "Market Street",
        streetNumber: "1200",
        city: "San Francisco",
        postalCode: "94103",
        state: "CA",
        country: "US",
        isDefaultShipping: false,
        isDefaultBilling: false,
      },
    ],
    associates: [
      {
        id: "assoc-1",
        customerId: "cst-1001",
        name: "Mia Johnson",
        email: "mia@northwind.com",
        roles: ["Admin", "Buyer"],
        status: "Active",
      },
      {
        id: "assoc-2",
        customerId: "cst-1004",
        name: "Robert Smith",
        email: "robert@northwind.com",
        roles: ["Buyer"],
        status: "Active",
      },
    ],
  },
  {
    id: "bu-102",
    name: "Northwind Retail - East Division",
    key: "northwind-east",
    status: "Active",
    unitType: "Division",
    parentId: "bu-101",
    parentName: "Northwind Retail Inc",
    storeKey: "us-flagship-store",
    createdAt: "2026-02-10T11:00:00Z",
    lastModifiedAt: "2026-07-15T16:00:00Z",
    creditLimit: 20000,
    creditUsed: 4200,
    addresses: [
      {
        id: "addr-103",
        companyName: "Northwind East Ops",
        streetName: "Boylston Street",
        streetNumber: "300",
        city: "Boston",
        postalCode: "02116",
        state: "MA",
        country: "US",
        isDefaultShipping: true,
        isDefaultBilling: true,
      },
    ],
    associates: [
      {
        id: "assoc-3",
        customerId: "cst-1005",
        name: "Emily Davis",
        email: "emily@northwind-east.com",
        roles: ["Approver"],
        status: "Active",
      },
    ],
  },
  {
    id: "bu-103",
    name: "Apex Digital Solutions Ltd",
    key: "apex-digital",
    status: "Active",
    unitType: "Company",
    storeKey: "global-b2b-store",
    createdAt: "2026-03-01T08:15:00Z",
    lastModifiedAt: "2026-08-05T10:45:00Z",
    creditLimit: 100000,
    creditUsed: 38900,
    addresses: [
      {
        id: "addr-104",
        companyName: "Apex Digital Towers",
        streetName: "Tech Park Way",
        streetNumber: "88",
        city: "Austin",
        postalCode: "78701",
        state: "TX",
        country: "US",
        isDefaultShipping: true,
        isDefaultBilling: true,
      },
    ],
    associates: [
      {
        id: "assoc-4",
        customerId: "cst-1002",
        name: "Rahul Mehta",
        email: "rahul@apexdigital.com",
        roles: ["Admin", "Approver", "Buyer"],
        status: "Active",
      },
    ],
  },
  {
    id: "bu-104",
    name: "Acme Industrial Supplies",
    key: "acme-industrial",
    status: "Inactive",
    unitType: "Company",
    storeKey: "us-flagship-store",
    createdAt: "2025-11-20T14:00:00Z",
    lastModifiedAt: "2026-06-10T09:12:00Z",
    creditLimit: 15000,
    creditUsed: 0,
    addresses: [
      {
        id: "addr-105",
        companyName: "Acme Logistics Center",
        streetName: "Industrial Blvd",
        streetNumber: "500",
        city: "Chicago",
        postalCode: "60607",
        state: "IL",
        country: "US",
        isDefaultShipping: true,
        isDefaultBilling: true,
      },
    ],
    associates: [],
  },
];
