"use client";

import { gql, useMutation, useQuery } from "@apollo/client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/shell/AppShell";
import { useCurrentUser } from "@/lib/use-current-user";

type Section = "users" | "roles" | "email" | "ai";
type Permission = { module: string; view: boolean; create: boolean; update: boolean; delete: boolean };
type Role = { id: string; key: string; label: string; description: string; system: boolean; permissions: Permission[] };

const WORKSPACE_ADMIN = gql`
  query WorkspaceAdmin($clientId: ID!, $projectKey: String!) {
    adminClient(id: $clientId) { id name contactEmail }
    adminProjectsByClient(clientId: $clientId) { id projectKey displayName smtpProfileId }
    adminUsersByClient(clientId: $clientId) { id email firstName lastName active clientProjects { projectKey role } }
    adminSmtpProfilesByClient(clientId: $clientId) { id name smtpHost smtpPort smtpSecure smtpUser smtpPasswordMasked emailFrom isDefault }
    adminRoles(clientId: $clientId, projectKey: $projectKey) { id key label description system permissions { module view create update delete } }
    adminAiSettings(clientId: $clientId) { enabled provider displayName model baseUrl apiKeySet updatedBy updatedAt }
  }
`;

const UPDATE_USER = gql`mutation UpdateWorkspaceUser($clientId: ID!, $input: AdminUpdateClientUserInput!, $grantedBy: String!) { adminUpdateClientUser(clientId: $clientId, input: $input, grantedBy: $grantedBy) { email } }`;
const UPDATE_CONTACT = gql`mutation UpdateContact($clientId: ID!, $contactEmail: String!) { adminUpdateClientContact(clientId: $clientId, contactEmail: $contactEmail) { id contactEmail } }`;
const CREATE_ROLE = gql`mutation CreateRole($clientId: ID!, $projectKey: String!, $input: AdminRoleInput!) { adminCreateRole(clientId: $clientId, projectKey: $projectKey, input: $input) { id } }`;
const UPDATE_ROLE = gql`mutation UpdateRole($id: ID!, $clientId: ID!, $projectKey: String!, $input: AdminRoleUpdateInput!) { adminUpdateRole(id: $id, clientId: $clientId, projectKey: $projectKey, input: $input) { id } }`;
const DELETE_ROLE = gql`mutation DeleteRole($id: ID!, $clientId: ID!, $projectKey: String!) { adminDeleteRole(id: $id, clientId: $clientId, projectKey: $projectKey) }`;
const CREATE_SMTP = gql`mutation CreateSmtp($clientId: ID!, $input: AdminSmtpProfileInput!) { adminCreateSmtpProfile(clientId: $clientId, input: $input) { id } }`;
const DELETE_SMTP = gql`mutation DeleteSmtp($id: ID!, $clientId: ID!) { adminDeleteSmtpProfile(id: $id, clientId: $clientId) }`;
const TEST_SMTP = gql`mutation TestSmtp($id: ID!, $clientId: ID!, $to: String) { adminTestSmtpProfile(id: $id, clientId: $clientId, to: $to) { ok message } }`;
const ROUTE_SMTP = gql`mutation RouteSmtp($clientId: ID!, $projectKey: String!, $smtpProfileId: String) { adminSetProjectSmtp(clientId: $clientId, projectKey: $projectKey, smtpProfileId: $smtpProfileId) }`;
const UPDATE_AI = gql`mutation UpdateAi($clientId: ID!, $input: AdminAiSettingsInput!) { adminUpdateAiSettings(clientId: $clientId, input: $input) { enabled provider displayName model baseUrl apiKeySet } }`;

const modules = ["dashboard", "tickets", "customers", "orders", "carts", "products", "reports", "knowledgebase", "assistant", "users", "roles", "email", "audit"];
const blankPermissions = () => modules.map((module) => ({ module, view: true, create: false, update: false, delete: false }));

export function AdminSettingsView({ section }: { section: Section }) {
  const { user, loading: userLoading } = useCurrentUser();
  const clientId = user?.activeClientId ?? "";
  const projectKey = user?.activeProjectKey ?? "";
  const allowed = user?.role === "admin" || user?.role === "superadmin";
  const { data, loading, error, refetch } = useQuery(WORKSPACE_ADMIN, { variables: { clientId, projectKey }, skip: !clientId || !projectKey || !allowed, fetchPolicy: "cache-and-network" });

  if (userLoading) return <AppShell><State text="Checking administrator access…" /></AppShell>;
  if (!allowed) return <AppShell><State text="Administrator access is required." /></AppShell>;
  if (!clientId || !projectKey) return <AppShell><State text="Select a project before opening Admin Settings." /></AppShell>;

  return <AppShell><div className="space-y-6 p-6">
    <div><p className="text-xs font-bold uppercase tracking-widest text-m-primary">Admin Settings</p><h1 className="text-2xl font-bold text-m-text">{data?.adminClient?.name ?? "Organisation"}</h1><p className="mt-1 text-sm text-m-text-muted">Settings apply to the active project. Switch projects in the header to manage another workspace.</p></div>
    <nav className="flex flex-wrap gap-2 rounded-xl border border-m-border bg-m-surface p-2" aria-label="Admin settings sections">
      {[["users","User Management","/admin/users"],["roles","Role Management","/admin/roles"],["email","Email Settings","/admin/settings/email"],["ai","AI Agent","/admin/settings/ai-agent"]].map(([id,label,href]) => <Link key={id} href={href} className={`rounded-lg px-4 py-2 text-sm font-semibold ${section === id ? "bg-m-primary text-white" : "text-m-text-muted hover:bg-m-surface-bg"}`}>{label}</Link>)}
    </nav>
    {loading ? <State text="Loading settings…" /> : error ? <State text={error.message} /> : section === "users" ? <Users data={data} clientId={clientId} projectKey={projectKey} actor={user?.email ?? ""} refetch={refetch} /> : section === "roles" ? <Roles roles={data.adminRoles} clientId={clientId} projectKey={projectKey} refetch={refetch} /> : section === "email" ? <EmailSettings data={data} clientId={clientId} refetch={refetch} /> : <AiSettings settings={data.adminAiSettings} clientId={clientId} refetch={refetch} />}
  </div></AppShell>;
}

function Users({ data, clientId, projectKey, actor, refetch }: { data: any; clientId: string; projectKey: string; actor: string; refetch: () => Promise<unknown> }) {
  const [search, setSearch] = useState(""); const [updateUser] = useMutation(UPDATE_USER); const roles: Role[] = data.adminRoles;
  const users = useMemo(() => data.adminUsersByClient.filter((u: any) => `${u.email} ${u.firstName ?? ""} ${u.lastName ?? ""}`.toLowerCase().includes(search.toLowerCase())), [data.adminUsersByClient, search]);
  async function changeRole(user: any, role: string) { const projects = user.clientProjects.map((p: any) => p.projectKey === projectKey ? { ...p, role } : { projectKey: p.projectKey, role: p.role }); await updateUser({ variables: { clientId, grantedBy: actor, input: { email: user.email, projects } } }); await refetch(); }
  return <section className="space-y-4"><div><h2 className="text-xl font-bold">User Management</h2><p className="text-sm text-m-text-muted">Manage roles for <strong>{projectKey}</strong>.</p></div><input aria-label="Search users" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search by email or name…" className="w-full rounded-lg border border-m-border bg-m-surface px-3 py-2"/><div className="overflow-auto rounded-xl border border-m-border bg-m-surface"><table className="w-full text-sm"><thead><tr className="border-b border-m-border text-left"><th className="p-3">Email</th><th>Name</th><th>Role ({projectKey})</th><th>Change Role</th></tr></thead><tbody>{users.map((u:any)=>{const membership=u.clientProjects.find((p:any)=>p.projectKey===projectKey); if(!membership)return null; return <tr key={u.id} className="border-b border-m-border"><td className="p-3 font-medium">{u.email}</td><td>{[u.firstName,u.lastName].filter(Boolean).join(" ")||"--"}</td><td>{membership.role}</td><td><select aria-label={`Change role for ${u.email}`} value={membership.role} onChange={(e)=>void changeRole(u,e.target.value)} className="rounded border border-m-border bg-m-surface px-2 py-1">{roles.map(r=><option key={r.key} value={r.key}>{r.label}</option>)}</select></td></tr>})}</tbody></table></div></section>;
}

function Roles({ roles, clientId, projectKey, refetch }: { roles: Role[]; clientId: string; projectKey: string; refetch: () => Promise<unknown> }) {
  const [selectedId,setSelectedId]=useState(roles[0]?.id??""); const selected=roles.find(r=>r.id===selectedId); const [createRole]=useMutation(CREATE_ROLE); const [updateRole]=useMutation(UPDATE_ROLE); const [deleteRole]=useMutation(DELETE_ROLE);
  async function add(){const key=`custom_${Date.now()}`; await createRole({variables:{clientId,projectKey,input:{key,label:"Custom Role",description:"Custom workspace role",permissions:blankPermissions()}}}); await refetch();}
  async function toggle(module:string,action:keyof Omit<Permission,"module">){if(!selected)return; const permissions=selected.permissions.map(p=>p.module===module?{...p,[action]:!p[action]}:p); await updateRole({variables:{id:selected.id,clientId,projectKey,input:{permissions}}}); await refetch();}
  return <section className="space-y-4"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Role Management</h2><p className="text-sm text-m-text-muted">Page and action permissions for {projectKey}.</p></div><button onClick={()=>void add()} className="rounded-lg bg-m-primary px-4 py-2 text-sm font-bold text-white">+ Add Role</button></div><div className="grid gap-4 lg:grid-cols-[280px_1fr]"><div className="space-y-2">{roles.map(r=><button key={r.id} onClick={()=>setSelectedId(r.id)} className={`w-full rounded-xl border p-4 text-left ${selectedId===r.id?"border-m-primary bg-m-primary-50":"border-m-border bg-m-surface"}`}><strong>{r.label}</strong><span className="ml-2 text-xs text-m-text-muted">{r.system?"System":r.key}</span><p className="mt-1 text-xs text-m-text-muted">{r.description}</p></button>)}</div>{selected&&<div className="overflow-auto rounded-xl border border-m-border bg-m-surface p-4"><div className="mb-3 flex justify-between"><h3 className="font-bold">{selected.label} ACL</h3>{!selected.system&&<button onClick={async()=>{await deleteRole({variables:{id:selected.id,clientId,projectKey}});setSelectedId("");await refetch();}} className="text-sm font-semibold text-m-error">Delete</button>}</div><table className="w-full text-sm"><thead><tr><th className="text-left">Module</th>{["view","create","update","delete"].map(a=><th key={a} className="p-2 capitalize">{a}</th>)}</tr></thead><tbody>{selected.permissions.map(p=><tr key={p.module} className="border-t border-m-border"><td className="py-2 capitalize">{p.module}</td>{(["view","create","update","delete"] as const).map(a=><td key={a} className="text-center"><input aria-label={`${selected.label} ${p.module} ${a}`} type="checkbox" checked={p[a]} onChange={()=>void toggle(p.module,a)}/></td>)}</tr>)}</tbody></table></div>}</div></section>;
}

function EmailSettings({ data, clientId, refetch }: { data: any; clientId: string; refetch: () => Promise<unknown> }) {
  const [contact,setContact]=useState(data.adminClient.contactEmail??""); const [showAdd,setShowAdd]=useState(false); const [form,setForm]=useState({name:"",smtpHost:"",smtpPort:587,smtpUser:"",smtpPassword:"",emailFrom:"",smtpSecure:false,isDefault:false}); const [status,setStatus]=useState(""); const [saveContact]=useMutation(UPDATE_CONTACT); const [createSmtp]=useMutation(CREATE_SMTP); const [deleteSmtp]=useMutation(DELETE_SMTP); const [testSmtp]=useMutation(TEST_SMTP); const [routeSmtp]=useMutation(ROUTE_SMTP);
  return <section className="space-y-6"><div><h2 className="text-xl font-bold">Email Settings</h2><p className="text-sm text-m-text-muted">Configure outbound email and project routing.</p></div><div className="rounded-xl border border-m-border bg-m-surface p-4"><label className="text-sm font-semibold">Organisation contact email</label><div className="mt-2 flex gap-2"><input value={contact} onChange={e=>setContact(e.target.value)} className="flex-1 rounded border border-m-border px-3 py-2"/><button onClick={async()=>{await saveContact({variables:{clientId,contactEmail:contact}});setStatus("Contact email saved")}} className="rounded bg-m-primary px-4 text-white">Save</button></div></div><div className="rounded-xl border border-m-border bg-m-surface p-4"><div className="flex justify-between"><h3 className="font-bold">SMTP profiles</h3><button onClick={()=>setShowAdd(!showAdd)} className="text-sm font-bold text-m-primary">+ Add profile</button></div>{showAdd&&<div className="mt-4 grid gap-2 md:grid-cols-2">{[["name","Label"],["smtpHost","Host"],["smtpUser","Username"],["smtpPassword","Password"],["emailFrom","From"]].map(([key,label])=><input key={key} type={key==="smtpPassword"?"password":"text"} placeholder={label} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="rounded border border-m-border px-3 py-2"/>)}<button onClick={async()=>{await createSmtp({variables:{clientId,input:form}});setShowAdd(false);await refetch()}} className="rounded bg-m-primary px-3 py-2 text-white">Save profile</button></div>}<div className="mt-4 space-y-2">{data.adminSmtpProfilesByClient.map((p:any)=><div key={p.id} className="flex flex-wrap items-center justify-between rounded-lg border border-m-border p-3"><div><strong>{p.name}</strong><p className="text-xs text-m-text-muted">{p.smtpHost}:{p.smtpPort} · {p.emailFrom}</p></div><div className="flex gap-3"><button onClick={async()=>{const result=await testSmtp({variables:{id:p.id,clientId,to:contact}});setStatus(result.data.adminTestSmtpProfile.message)}} className="text-sm text-m-primary">Test</button><button onClick={async()=>{await deleteSmtp({variables:{id:p.id,clientId}});await refetch()}} className="text-sm text-m-error">Delete</button></div></div>)}</div></div><div className="rounded-xl border border-m-border bg-m-surface p-4"><h3 className="font-bold">Project routing</h3>{data.adminProjectsByClient.map((p:any)=><div key={p.id} className="mt-3 flex items-center justify-between"><code>{p.projectKey}</code><select value={p.smtpProfileId??""} onChange={async e=>{await routeSmtp({variables:{clientId,projectKey:p.projectKey,smtpProfileId:e.target.value||null}});await refetch()}} className="rounded border border-m-border p-2"><option value="">Organisation default</option>{data.adminSmtpProfilesByClient.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>)}</div>{status&&<p role="status" className="text-sm text-m-success-dark">{status}</p>}</section>;
}

function AiSettings({ settings, clientId, refetch }: { settings: any; clientId: string; refetch: () => Promise<unknown> }) {
  const [form,setForm]=useState({...settings,apiKey:""}); const [saved,setSaved]=useState(false); const [updateAi]=useMutation(UPDATE_AI);
  return <section className="max-w-3xl space-y-4"><div><h2 className="text-xl font-bold">AI Agent</h2><p className="text-sm text-m-text-muted">Configure the assistant provider for this organisation. API keys are encrypted and never returned.</p></div><div className="space-y-4 rounded-xl border border-m-border bg-m-surface p-5"><label className="flex gap-2"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Use organisation AI configuration</label><label className="block text-sm font-semibold">Provider<select value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})} className="mt-1 w-full rounded border border-m-border p-2"><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Google Gemini</option><option value="other">Other (OpenAI-compatible)</option></select></label>{[["displayName","Display name"],["model","Model"],["baseUrl","API base URL"],["apiKey",settings.apiKeySet?"API key (leave blank to keep existing)":"API key"]].map(([key,label])=><label key={key} className="block text-sm font-semibold">{label}<input type={key==="apiKey"?"password":"text"} value={form[key]??""} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded border border-m-border p-2"/></label>)}<button onClick={async()=>{await updateAi({variables:{clientId,input:{enabled:form.enabled,provider:form.provider,displayName:form.displayName,model:form.model,baseUrl:form.baseUrl||null,apiKey:form.apiKey||null}}});setSaved(true);await refetch()}} className="rounded bg-m-primary px-4 py-2 font-bold text-white">Save AI agent settings</button>{saved&&<span className="ml-3 text-sm text-m-success-dark">Saved</span>}</div></section>;
}

function State({ text }: { text: string }) { return <div className="p-8 text-sm text-m-text-muted">{text}</div>; }
