import { docs } from "@/.source";
import { loader } from "fumadocs-core/source";

// fumadocs-mdx builds the source's `files` as a lazy function
// (`files: () => resolveFiles(...)`), whereas fumadocs-core's `loader` reads
// `files` as an array. Normalize `files` to an array so the two interoperate
// regardless of which side is lazy.
const mdxSource = docs.toFumadocsSource();
const rawFiles = (mdxSource as unknown as { files: unknown }).files;
const files = (
  typeof rawFiles === "function" ? (rawFiles as () => unknown[])() : rawFiles
) as typeof mdxSource.files;

// The single content source that powers the sidebar tree, page lookups and
// search. `docs` is generated by `fumadocs-mdx` into ./.source from
// content/docs (see source.config.ts).
export const source = loader({
  baseUrl: "/docs",
  source: { ...mdxSource, files }
});
