import type { Employee } from "../types/employee-types";

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: "cst-1001",
    customerNumber: "EMP-9001",
    externalId: "EXT-NW-01",
    firstName: "Mia",
    lastName: "Johnson",
    email: "mia@northwind.com",
    phone: "+1 (555) 234-5678",
    dateOfBirth: "1988-04-12",
    customerGroup: "B2B Buyers",
    status: "Active",
    createdAt: "2026-01-16T10:00:00Z",
    lastModifiedAt: "2026-08-01T11:30:00Z",
    memberships: [
      {
        companyId: "bu-101",
        companyName: "Northwind Retail Inc",
        companyKey: "northwind-retail",
        roles: ["Admin", "Buyer"],
      },
    ],
    addresses: [
      {
        id: "eaddr-1",
        streetName: "Fifth Avenue",
        streetNumber: "742",
        city: "New York",
        postalCode: "10001",
        state: "NY",
        country: "US",
        isDefaultShipping: true,
        isDefaultBilling: true,
      },
    ],
  },
  {
    id: "cst-1002",
    customerNumber: "EMP-9002",
    externalId: "EXT-APEX-01",
    firstName: "Rahul",
    lastName: "Mehta",
    email: "rahul@apexdigital.com",
    phone: "+1 (555) 987-6543",
    dateOfBirth: "1985-09-20",
    customerGroup: "B2B VIP",
    status: "Active",
    createdAt: "2026-03-02T12:00:00Z",
    lastModifiedAt: "2026-08-05T09:15:00Z",
    memberships: [
      {
        companyId: "bu-103",
        companyName: "Apex Digital Solutions Ltd",
        companyKey: "apex-digital",
        roles: ["Admin", "Approver", "Buyer"],
      },
    ],
    addresses: [
      {
        id: "eaddr-2",
        streetName: "Tech Park Way",
        streetNumber: "88",
        city: "Austin",
        postalCode: "78701",
        state: "TX",
        country: "US",
        isDefaultShipping: true,
        isDefaultBilling: true,
      },
    ],
  },
  {
    id: "cst-1003",
    customerNumber: "EMP-9003",
    externalId: "EXT-NW-02",
    firstName: "Sofia",
    lastName: "Garcia",
    email: "sofia@northwind.com",
    phone: "+1 (555) 345-6789",
    dateOfBirth: "1992-11-05",
    customerGroup: "B2B Buyers",
    status: "Active",
    createdAt: "2026-02-01T09:00:00Z",
    lastModifiedAt: "2026-07-20T15:45:00Z",
    memberships: [
      {
        companyId: "bu-101",
        companyName: "Northwind Retail Inc",
        companyKey: "northwind-retail",
        roles: ["Buyer"],
      },
    ],
    addresses: [],
  },
  {
    id: "cst-1004",
    customerNumber: "EMP-9004",
    externalId: "EXT-NW-03",
    firstName: "Robert",
    lastName: "Smith",
    email: "robert@northwind.com",
    phone: "+1 (555) 456-7890",
    dateOfBirth: "1990-01-30",
    customerGroup: "B2B Buyers",
    status: "Active",
    createdAt: "2026-02-15T14:20:00Z",
    lastModifiedAt: "2026-07-18T10:00:00Z",
    memberships: [
      {
        companyId: "bu-101",
        companyName: "Northwind Retail Inc",
        companyKey: "northwind-retail",
        roles: ["Buyer"],
      },
    ],
    addresses: [],
  },
  {
    id: "cst-1005",
    customerNumber: "EMP-9005",
    externalId: "EXT-NWE-01",
    firstName: "Emily",
    lastName: "Davis",
    email: "emily@northwind-east.com",
    phone: "+1 (555) 567-8901",
    dateOfBirth: "1995-07-14",
    customerGroup: "B2B Approvers",
    status: "Active",
    createdAt: "2026-02-12T10:30:00Z",
    lastModifiedAt: "2026-07-15T16:20:00Z",
    memberships: [
      {
        companyId: "bu-102",
        companyName: "Northwind Retail - East Division",
        companyKey: "northwind-east",
        roles: ["Approver"],
      },
    ],
    addresses: [],
  },
];
